travis:
  secure:
    BINSTAR_TOKEN: Twd82Q3M73BAgLVPpsCF4avEd8gEYFOfGvYOLuvRBBkrYzdqzc6rZC011GhO7yuf4bTps3Kv8VYkbnVDYglAkJEpD9XLEJ1awZNagW5efqu8s8Xqq2hca18tmeL6hA6zDq2QD7pXnuTpY14HkVfOx/gnpeYRw7c1FP5lFx7VV32PUOVZsjChhjwm0E0zLGhwPSofi69sQ6cI1ctbQoW9G4b8f02CqdDHywkRsJxa6eygBnBFMTVh290NZ6q22md9hze7S/SarJkEnilR43wcFILAGyJ5ho0oz84fw7zcelaopnRY4Xr/EEXQVQxwTFftWbSZRxxQsdm/ImBy2Vj/MFbK12kWtm/EpbRDS9S2V7RS71jh3xtZFiZv9KJp60BJCaO34v3NUXkjVIsJnpQ0DWtPgk30SnzK/d+0th6G7cHV9TAYpMtctwRY9Lzql1n/uXmdho1hnIHkuVrJG7XbomS2fmiJyoYRaQlK+XZvwzE2b8YjWv9uq5V0zQlZJIUxNMNf4KI374UpHZGDZtGqN1fIhk387HiRghT9+4lh/o/ILcD4sKMHbbGtL8O+AgKZ2DJLFB/+vXADzgZIV2xdMvFHEAcrzyPCHUtSvoMFvuyQ4gwVBUttYgK6m2KNLOmBVCDpKItFSNG5I9rbI7uDM70Asj+NYBEgU9QG4skZ8hQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
