travis:
  secure:
    BINSTAR_TOKEN: rFi7E/5V/8SYV1mQoa1lgfANKr01Y+N0M7iTJNXbEIeoCDfm3EO1y+3bsNf6WCBeV8OcCbCngTyCKEXvGjWvPDhWSMZPlTihyU0Z1PZnwSWWQbtK4SjQeKg9w27NMxLVyC3oDqrbn7Nkiuqa2icKWSyx0CfqPHUKfQhwUTtKmnrBcERy+aISwxAD/bE6BORiai12Z74L07foA3tWEF62ze5I1IaYmIGUQRNMmydDROfhdALvyv4DgiQBCQTLdy0ptr6TnxAc0HZ5Fra2Zni47qrIdaj+FNi60h73sRO4FTrsk4owQ8zdNGF43kNYxAi2xDLHr+Ia7Gd7g40ZGzMPs4BGNflT/7GG6ACKFCFdbCepFVgHWCGej/YPKL+zsLoH+EUGfrnW5cVY1pfH2UStAnAy3wJ0S8pK/Bzy1815waDTBkMHPmDF4ZBCLjd885dp0u66KhHhaYcr7brwSF9rb4OPtkR+Hj1jCErtuZv8i8mFxtJa19RAnUj1/qVL6ljR1gWGWo2NJTL6fDqVTGIpc+1LYuggzhFGh4WbeaZ3WPPmxVct2ZbhV0qXPD9C9J2HWzv6KJnEURgbx1tI0ALtbFr+520wE9gcuEHL3q7ojq3EWn8Baw/iDjysjc3+qV9mgLyGKPnBp3mk/TmU/z6w9oj/LF1q0tDBuXdni02SNfg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
