travis:
  secure:
    BINSTAR_TOKEN: F+imlGreuGG3MZ+Zo5PVvMrIFqdGuuaGsI3UIxBlQd4usd4Bq83J1/2nLZqT/w0cqzwycbbIbrH4gdY8oOBJ71KQ0hy7Ybz5ftHAIuul9GfR0O8mzh3etwg4XHxmWKb1CI/cCqStKGp9EsRmwv9sG/9TYN/sW0jaQ6jOcaqdbg18YPypW8XRRIzzP2e8qVazq0A3V6UsChHsfGqMqj24qB6dDiFm56ikU7WnfsxfOGdX6uM1vHJa1JYMti6amV0hQErgKCmam0XTSDN6xh72r19kj+1iD/MeXixaSVZfIVSAe3RtRO2hM3ttFe+PfRYm7EOI6CT97LjrqMmSITSKF4eAAagS/1R4cHZpsP+vqVVhTtDj8VfMJLQiSmfiPFTv8DYBMMkY1Mq6daAZD8nU3hU84Mtnw4Ht56Q1GmRx/PJHP042tnoaaoWamJX72Jvv5zqbrBkbQ85Y2KLm9XL2+wS3zveBp8N7QmrAUZHLRAj6giSQNm1yG3U1VMZr3SlQr0+YYwYdud4JwG2bIdipHN54950zxYIFh/vPMMoanK0Ci1LgdQEJ6xV4R2LMdE/ktRPALIlqdkXvrrxq3SOVS1L0t2ZOs8IUyS6qzYZQbK9SZY/HGOuNvrrXxCX28LHFbZ11Zux5TbgL4/gZ4JdlyLVojvvKufp3FthPSp/lTpU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
