travis:
  secure:
    BINSTAR_TOKEN: ToGN+8MLjZLzyWANvA35mDUCuiOOW+69cImUi1cv6pIUfBSgApmVifiqRWjl4izvIOgTvKZ/2buyDzFjns+mAPbZcrbn8NXlzOsyvcEyvRfd/00ds65qAYAx0qCy2nn/wJpgZOFLoiW7zAd618L2WbK3GTMMMIZX+UcHjhJXjCLkWCScj5+VC6VCZV7A2x6KDQnWm3HsJV9Z/67JSXMrRI+lzfnl9HXooSfnBSiqoZGze61MePfqHfJWcsX91eCv6p7Jr7sFsMIyTJ0cdD+h0dvZ4y7Pn0TPCPChkWvsgQcNgGdqwZ1PPXOVMWaZKXq5sxCq6MfW/mZvWIpGZes1dgJ6UjkV5JFiXTcDZTEtBMAGao3myU2rR7HjjgZI8h/pbdMY6eceUVJ65OmKgubis223icW6125Bqwgjp2FKn5+qpjVVt2TBUl9nfnzLs8GlNKhkz15Ljgw7bCMqFHSMaodiI0UaEu5pQ42Te1Rha3EjTc8vJFk7UVodBFuKoOiSS42W9sFQlVryOkRr8nASMG5skM7R0dapH1rL1ychI9Uh1sCBBfqrR32VT7ff6EL7LiI0yItmApkcFO8+qdq2h/OyRJ6UxWai3SESB+4rFxrRDsdbg9pGNqA72YofZ88h/0SuYbAIi7K+JToNrDs+7LnDfCEE4AIa8o65/mj4zIw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
